In [1]:
import pandas as pd
import numpy as np
import re

Downloading the Twitts dataset from my own Github repo

In [2]:
ds = pd.read_csv("https://github.com/FarshadAmiri/Learning-NLP/blob/main/Word%20Vectors%20(Embeddings)/Word2Vec%20on%20Twitts/train.csv?raw=true")
ds = ds.Text
ds_org = ds
ds

0         Reuters - Short-sellers, Wall Street's dwindli...
1         Reuters - Private investment firm Carlyle Grou...
2         Reuters - Soaring crude prices plus worries\ab...
3         Reuters - Authorities have halted oil export\f...
4         AFP - Tearaway world oil prices, toppling reco...
                                ...                        
119995     KARACHI (Reuters) - Pakistani President Perve...
119996    Red Sox general manager Theo Epstein acknowled...
119997    The Miami Dolphins will put their courtship of...
119998    PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...
119999    INDIANAPOLIS -- All-Star Vince Carter was trad...
Name: Text, Length: 120000, dtype: object

Impelementing various modifications on the twitts texts via Regex

In [3]:
ds = [re.sub(r'\\',' ',i) for i in ds]
ds = [re.sub(r'^.{3,40}-- ',' ',i) for i in ds]
ds = [re.sub(r'^.{3,30}- ',' ',i) for i in ds]
ds = [i.strip() for i in ds]
ds = [re.sub(r'.$','',i) for i in ds]
ds = [re.sub(r'(\w*)\.','\g<1>',i) for i in ds]
ds = [re.sub(r'&lt.*?&gt',' ', i) for i in ds]
ds = [re.sub(r'\d+','', i) for i in ds]
ds = [re.sub(r'[#@$;,!*?=]','', i) for i in ds]
ds = [re.sub(r'[_/\\]',' ', i) for i in ds]
ds = [re.sub(r'-',' ', i) for i in ds]
ds = [re.sub(r':','', i) for i in ds]
ds = [re.sub(r'\.{2,10}',' ', i) for i in ds]
ds = [re.sub(r'   ',' ', i) for i in ds]
ds = [re.sub(r'  ',' ', i) for i in ds]
ds = [re.sub(r'\(','', i) for i in ds]
ds = [re.sub(r'\)','', i) for i in ds]
ds = [re.sub(r'\)','', i) for i in ds]
ds = [re.sub(r'\. ',' ', i) for i in ds]
ds = [re.sub(r'\. ',' ', i) for i in ds]
ds = [re.sub(r'wasn\'t','was not', i) for i in ds]
ds = [re.sub(r'hasn\'t','has not', i) for i in ds]
ds = [re.sub(r'haven\'t','have not', i) for i in ds]
ds = [re.sub(r'isn\'t','is not', i) for i in ds]
ds = [re.sub(r'won\'t','will not', i) for i in ds]
ds = [re.sub(r'couln\'t','could not', i) for i in ds]
ds = [re.sub(r'wouln\'t','would not', i) for i in ds]
ds = [re.sub(r' \"',' ', i) for i in ds]
ds = [re.sub(r'\" ',' ', i) for i in ds]
ds = [re.sub(r'\"','', i) for i in ds]
ds = [re.sub(r'^\'','', i) for i in ds]
ds = [re.sub(r'^\'\'','', i) for i in ds]
ds = [re.sub(r' \'\'','', i) for i in ds]
ds = [re.sub(r'^\"','', i) for i in ds]
ds = [re.sub(r' \'',' ', i) for i in ds]
ds = [re.sub(r' \'',' ', i) for i in ds]
ds = [re.sub(r'\' ',' ', i) for i in ds]
ds = [re.sub(r'^\'','', i) for i in ds]
ds = [re.sub(r'\'s ',' ', i) for i in ds]
ds = [re.sub(r' _ ',' ', i) for i in ds]
ds = [re.sub(r' s ',' ', i) for i in ds]
ds = [re.sub(r'   ',' ', i) for i in ds]
ds = [re.sub(r'  ',' ', i) for i in ds]
ds = [re.sub(r'&gt','', i) for i in ds]
ds = [re.sub(r'&(l|L)(t|T)(m|M)(e|E)(t|T)(a|A)','', i) for i in ds]
ds = [re.sub(r'&(l|L)(t|T)(s|S)cript','', i) for i in ds]
ds = [re.sub(r'\.(.*? )', '\g<1>', i) for i in ds]
ds = [re.sub(r'\.(.*? )', '\g<1>', i) for i in ds]
ds = [re.sub(r'\.(.*? )', '\g<1>', i) for i in ds]
ds = [re.sub(r' \. ', ' ', i) for i in ds]
ds = [re.sub(r'   ',' ', i) for i in ds]
ds = [re.sub(r'  ',' ', i) for i in ds]
ds = [i.lower() for i in ds]
ds = [i.strip() for i in ds]
ds

['short sellers wall street dwindling band of ultra cynics are seeing green again',
 'private investment firm carlyle group which has a reputation for making well timed and occasionally controversial plays in the defense industry has quietly placed its bets on another part of the market',
 'soaring crude prices plus worries about the economy and the outlook for earnings are expected to hang over the stock market next week during the depth of the summer doldrums',
 'authorities have halted oil export flows from the main pipeline in southern iraq after intelligence showed a rebel militia could strike infrastructure an oil official said on saturday',
 'tearaway world oil prices toppling records and straining wallets present a new economic menace barely three months before the us presidential elections',
 'stocks ended slightly higher on friday but stayed near lows for the year as oil prices surged past a barrel offsetting a positive outlook from computer maker dell inc dello',
 'assets of

A brief and simple Data Inspection

In [4]:
total_words = 0
vocabs = dict()
for line in ds:
  for w in line.split(' '):
    total_words += 1
    if w.lower() in vocabs.keys():
      vocabs[w.lower()] += 1
    else:
      vocabs[w.lower()] = 1
print(f"Total Number of words used in the dataset is {total_words}")
print(f"The number of unique words in the dataset is {len(vocabs)}")
print(f"Ratio of the total words to the unique words = {total_words/len(vocabs):.2f}")

Total Number of words used in the dataset is 3580678
The number of unique words in the dataset is 64080
Ratio of the total words to the unique words = 55.88


In [5]:
# Vocabs is a dictionary which contains the words which apperaed in the dataset (as the key) as well as the number of their appearance (the value).
vocabs = {k: v for k, v in sorted(vocabs.items(), key=lambda item: item[1], reverse = True)}
vocabs_ascending = {k: v for k, v in sorted(vocabs.items(), key=lambda item: item[1], reverse = False)}
vocabs

{'the': 197980,
 'a': 103796,
 'to': 96374,
 'of': 89348,
 'in': 78519,
 'and': 66300,
 'on': 47941,
 'for': 38082,
 'that': 27637,
 'with': 22614,
 'as': 21844,
 'its': 21204,
 'at': 20763,
 'is': 20061,
 'said': 20017,
 'it': 19084,
 'by': 18510,
 'has': 18313,
 'an': 16764,
 'from': 15735,
 'us': 14648,
 'his': 14366,
 'new': 13960,
 'will': 13647,
 'was': 13466,
 'after': 12503,
 'have': 10711,
 'be': 10381,
 'their': 10214,
 'two': 9200,
 'are': 9115,
 'over': 8940,
 'year': 8898,
 'first': 8557,
 'he': 8502,
 'but': 8295,
 'this': 7732,
 'more': 7645,
 'monday': 7473,
 'wednesday': 7433,
 'tuesday': 7369,
 'one': 7328,
 'up': 7313,
 'thursday': 7275,
 'company': 7266,
 'world': 7124,
 'inc': 6778,
 'friday': 6774,
 'not': 6321,
 'than': 6296,
 'last': 6142,
 'yesterday': 6067,
 'they': 5998,
 'against': 5915,
 'about': 5877,
 'who': 5807,
 'were': 5705,
 'into': 5676,
 'out': 5632,
 'three': 5495,
 'president': 5483,
 'been': 5443,
 'had': 5153,
 'week': 5145,
 'million': 5059,
 

In [6]:
vocabs_ascending

{'tearaway': 1,
 'sociology': 1,
 'bazil': 1,
 'brochures': 1,
 'oversupplied': 1,
 'baylis': 1,
 'freeplay': 1,
 'cofounded': 1,
 'parceled': 1,
 'aggressiveness': 1,
 'baileysummer': 1,
 'sizzler': 1,
 'otherwiseuzis': 1,
 'hasturned': 1,
 'nobility': 1,
 'creepie': 1,
 'webpreneurs': 1,
 'astorga': 1,
 'characterize': 1,
 'goaded': 1,
 'impishly': 1,
 'pinoy': 1,
 'lampano': 1,
 'bluegrass': 1,
 'livability': 1,
 'ornately': 1,
 'albino': 1,
 'buggers': 1,
 'gaucherin': 1,
 'buzzsaw': 1,
 'wrests': 1,
 'voicemails': 1,
 'farkcom': 1,
 'rowboats': 1,
 'procrastinating': 1,
 'nbspexciting': 1,
 'nbspget': 1,
 'armadillo': 1,
 'mesquite': 1,
 'mowed': 1,
 'loosestrife': 1,
 'clannish': 1,
 'agressive': 1,
 'supercolony': 1,
 'outshining': 1,
 'reformulated': 1,
 'stargazing': 1,
 'noticing': 1,
 'subterranean': 1,
 'guinn': 1,
 'nested': 1,
 'seafloor': 1,
 'tectonics': 1,
 'subsoil': 1,
 'voyagers': 1,
 'cowbirds': 1,
 'cowbird': 1,
 'nbspat': 1,
 'nastiness': 1,
 'hypotheses': 1,
 'g

Creating more Data Inspection tools

In [7]:
# Defining a function which calculates the total number of words that has a specific number of concurrent in the dataset.
# For e.g "concurrent(vocabs, 2) = 9847" means that there are 9847 words which have just 2 times of concurrent through the whole dataset.
def concurrent_number(dictionary, number_of_concurrents):
  try:
    number_of_concurrents[1]
    criteria = True
    x1 = number_of_concurrents[0]
    x2 = number_of_concurrents[1]
  except:
    criteria = False
  def concurrent_specific(dict, concurrents):
    sum = 0
    for w in dict.keys():
      if dict[w] == concurrents:
        sum += 1
    return sum

  if criteria == False:
    return concurrent_specific(dictionary, number_of_concurrents)
  if criteria == True:
    sum_occ = 0
    for i in range(x1,x2+1):
      sum_occ += int(concurrent_number(vocabs, i))

    return sum_occ

In [8]:
# A function which enables you to know which words have a specific range of concurrents in the dataset.
# You can pass the "number of concurrents" both as a specific number or as an interval.
def concurrnet_words (dictionary, number_of_concurrents):
  try:
    number_of_concurrents[1]
    criteria = True
    x1 = number_of_concurrents[0]
    x2 = number_of_concurrents[1]
  except:
    criteria = False
  if criteria == True:
    for w in dictionary.keys():
      if (dictionary[w] > x1) and (dictionary[w] < x2):
        print(w)
  if criteria == False:
    for w in dictionary.keys():
      if dictionary[w] == number_of_concurrents:
        print(w)

In [9]:
print(concurrent_number(vocabs, 1))
print(concurrent_number(vocabs, 2))
print(concurrent_number(vocabs, 3))
print(concurrent_number(vocabs, (1,3)))

24228
8159
4644
37031


In [10]:
concurrnet_words(vocabs, (10000,50000))

on
for
that
with
as
its
at
is
said
it
by
has
an
from
us
his
new
will
was
after
have
be
their


**Creating Features and Labels (X and Y)**

Continuous Bag of Words (CBOW) moving window function:

In [11]:
def cbow_xy_maker(dataset, window_size=7):
  import math
  half_window = math.floor(window_size/2)
  x, y= [], []
  for sentence in dataset:
    sentence = sentence.split()
    if len(sentence) >= window_size:
        for w in range(half_window, len(sentence)-half_window):
          features = sentence[w-half_window : w+half_window+1]
          target = features[half_window]
          del features[half_window]
          x.append(features)
          y.append(target)

  return x, y

In [12]:
x,y = cbow_xy_maker(ds, window_size=7)

In [13]:
print(x[100:110])
print(y[100:110])

[['friday', 'but', 'stayed', 'lows', 'for', 'the'], ['but', 'stayed', 'near', 'for', 'the', 'year'], ['stayed', 'near', 'lows', 'the', 'year', 'as'], ['near', 'lows', 'for', 'year', 'as', 'oil'], ['lows', 'for', 'the', 'as', 'oil', 'prices'], ['for', 'the', 'year', 'oil', 'prices', 'surged'], ['the', 'year', 'as', 'prices', 'surged', 'past'], ['year', 'as', 'oil', 'surged', 'past', 'a'], ['as', 'oil', 'prices', 'past', 'a', 'barrel'], ['oil', 'prices', 'surged', 'a', 'barrel', 'offsetting']]
['near', 'lows', 'for', 'the', 'year', 'as', 'oil', 'prices', 'surged', 'past']


Creating Some Debugging tools (to amend text twitts modification codes (regex))

In [14]:
# Defining a function which returns the indice of the twitt in the dataset which contains some words.
# Afterwards, we can 
def contains_these_words(dataset, *words):
  words_appearance_dict = dict()
  for i,w in enumerate(words):
    appearance_boolean = dataset.str.contains(w, flags=re.IGNORECASE, regex=False)
    words_appearance_dict[w] = set([i for i, x in enumerate(appearance_boolean) if x])
    try:
      intersect = intersect.intersection(words_appearance_dict[w])
    except:
      intersect = words_appearance_dict[w]
  if len(intersect) == 0:
    return 'Nothing!' 
  else:
    return intersect

In [15]:
contains_these_words(ds_org, 'hospitals', 'company')

{68657, 68672, 68891, 68919, 87643}

In [16]:
contains_these_words(ds_org, 'addin')

{632,
 680,
 1400,
 3581,
 3955,
 4021,
 4916,
 5140,
 5182,
 5347,
 7868,
 7907,
 8037,
 9099,
 9755,
 10460,
 10924,
 10975,
 11048,
 11069,
 11605,
 11703,
 11713,
 11999,
 12449,
 13213,
 13253,
 13374,
 13560,
 13803,
 14507,
 14724,
 14984,
 15721,
 16552,
 16877,
 17694,
 17940,
 18270,
 18471,
 19187,
 19373,
 19656,
 19748,
 20511,
 20904,
 20959,
 21487,
 21902,
 21922,
 23332,
 23355,
 23442,
 23916,
 24006,
 24011,
 24244,
 26204,
 27180,
 27181,
 27525,
 28328,
 28438,
 28483,
 28705,
 29989,
 30406,
 30706,
 31939,
 32468,
 33107,
 33546,
 34253,
 34556,
 34591,
 34755,
 34816,
 35134,
 35821,
 37592,
 37630,
 38329,
 38365,
 39197,
 39758,
 39913,
 40192,
 40591,
 41094,
 41304,
 42463,
 43257,
 44272,
 45278,
 45624,
 45968,
 45969,
 46194,
 46384,
 46392,
 46911,
 47015,
 47166,
 47603,
 49297,
 49683,
 49987,
 50008,
 50197,
 50301,
 50447,
 50715,
 50801,
 51223,
 51463,
 51472,
 51550,
 52118,
 52259,
 52450,
 52465,
 52644,
 53214,
 53270,
 53280,
 53736,
 53766,
 

In [17]:
ds[20511]

'intel corp which has led the charge in the gigahertz race is expected to change its tune at this week developer forum in san francisco by focusing on improving chip performance by adding more cores to the microprocessor'

In [18]:
ds[68919]

'hca inc hcan the largest us hospital chain said on friday its third quarter earnings fell hurt by hurricanes that hit the southeastern united states earlier this year causing disruption and a drop in admissions at the company hospitals in florida'

In [19]:
ds_org.iloc[68919]

' NEW YORK (Reuters) - HCA Inc. &lt;A HREF="http://www.investor.reuters.com/FullQuote.aspx?ticker=HCA.N target=/stocks/quickinfo/fullquote"&gt;HCA.N&lt;/A&gt;, the largest U.S.  hospital chain, said on Friday its third-quarter earnings fell,  hurt by hurricanes that hit the southeastern United States  earlier this year, causing disruption and a drop in admissions  at the company\'s hospitals in Florida.'

In [20]:
vocabs['critical']

297

Creating Word2Token and Token2Word Dictionaries

In [21]:
words = sorted(list(vocabs.keys()))
print(words[:100])

['a', 'aa', 'aaa', 'aac', 'aacbto', 'aachen', 'aai', 'aaii', 'aain', 'aal', 'aalborg', 'aaliyah', 'aan', 'aanys', 'aap', 'aapl', 'aaplnas', 'aaplnasdaq', 'aaplo', 'aapt', 'aarde', 'aardsma', 'aaron', 'aasketball', 'aathar', 'aau', 'ab', 'ababa', 'abacha', 'abaco', 'abagnale', 'abakus', 'abando', 'abandon', 'abandoned', 'abandoning', 'abandonment', 'abandons', 'abare', 'abarrel', 'abate', 'abated', 'abating', 'abaya', 'abb', 'abbas', 'abbass', 'abbe', 'abbey', 'abbn', 'abbnvx', 'abbott', 'abboud', 'abbreviate', 'abbreviated', 'abbreviations', 'abby', 'abc', "abc's", 'abcn', 'abcnews', 'abcs', 'abd', 'abdalla', 'abdallah', 'abdel', 'abdelkrim', 'abdellah', 'abdelmalek', 'abdelraham', 'abdelrahim', 'abdelrahman', 'abderrazak', 'abdicate', 'abdicated', 'abdicating', 'abdication', 'abdomen', 'abdominal', 'abdoulaye', 'abduct', 'abducte', 'abducted', 'abductee', 'abductees', 'abducting', 'abduction', 'abductions', 'abductors', 'abdul', 'abdulahi', 'abdullah', 'abdullahi', 'abdur', 'abdurahma

In [22]:
word2tok = dict()
for i, w in enumerate(words):
  word2tok[w] = i

word2tok

{'a': 0,
 'aa': 1,
 'aaa': 2,
 'aac': 3,
 'aacbto': 4,
 'aachen': 5,
 'aai': 6,
 'aaii': 7,
 'aain': 8,
 'aal': 9,
 'aalborg': 10,
 'aaliyah': 11,
 'aan': 12,
 'aanys': 13,
 'aap': 14,
 'aapl': 15,
 'aaplnas': 16,
 'aaplnasdaq': 17,
 'aaplo': 18,
 'aapt': 19,
 'aarde': 20,
 'aardsma': 21,
 'aaron': 22,
 'aasketball': 23,
 'aathar': 24,
 'aau': 25,
 'ab': 26,
 'ababa': 27,
 'abacha': 28,
 'abaco': 29,
 'abagnale': 30,
 'abakus': 31,
 'abando': 32,
 'abandon': 33,
 'abandoned': 34,
 'abandoning': 35,
 'abandonment': 36,
 'abandons': 37,
 'abare': 38,
 'abarrel': 39,
 'abate': 40,
 'abated': 41,
 'abating': 42,
 'abaya': 43,
 'abb': 44,
 'abbas': 45,
 'abbass': 46,
 'abbe': 47,
 'abbey': 48,
 'abbn': 49,
 'abbnvx': 50,
 'abbott': 51,
 'abboud': 52,
 'abbreviate': 53,
 'abbreviated': 54,
 'abbreviations': 55,
 'abby': 56,
 'abc': 57,
 "abc's": 58,
 'abcn': 59,
 'abcnews': 60,
 'abcs': 61,
 'abd': 62,
 'abdalla': 63,
 'abdallah': 64,
 'abdel': 65,
 'abdelkrim': 66,
 'abdellah': 67,
 'abdelm

In [23]:
tok2word = {token: word for word, token in word2tok.items()}
tok2word

{0: 'a',
 1: 'aa',
 2: 'aaa',
 3: 'aac',
 4: 'aacbto',
 5: 'aachen',
 6: 'aai',
 7: 'aaii',
 8: 'aain',
 9: 'aal',
 10: 'aalborg',
 11: 'aaliyah',
 12: 'aan',
 13: 'aanys',
 14: 'aap',
 15: 'aapl',
 16: 'aaplnas',
 17: 'aaplnasdaq',
 18: 'aaplo',
 19: 'aapt',
 20: 'aarde',
 21: 'aardsma',
 22: 'aaron',
 23: 'aasketball',
 24: 'aathar',
 25: 'aau',
 26: 'ab',
 27: 'ababa',
 28: 'abacha',
 29: 'abaco',
 30: 'abagnale',
 31: 'abakus',
 32: 'abando',
 33: 'abandon',
 34: 'abandoned',
 35: 'abandoning',
 36: 'abandonment',
 37: 'abandons',
 38: 'abare',
 39: 'abarrel',
 40: 'abate',
 41: 'abated',
 42: 'abating',
 43: 'abaya',
 44: 'abb',
 45: 'abbas',
 46: 'abbass',
 47: 'abbe',
 48: 'abbey',
 49: 'abbn',
 50: 'abbnvx',
 51: 'abbott',
 52: 'abboud',
 53: 'abbreviate',
 54: 'abbreviated',
 55: 'abbreviations',
 56: 'abby',
 57: 'abc',
 58: "abc's",
 59: 'abcn',
 60: 'abcnews',
 61: 'abcs',
 62: 'abd',
 63: 'abdalla',
 64: 'abdallah',
 65: 'abdel',
 66: 'abdelkrim',
 67: 'abdellah',
 68: 'ab

Transforming X and Y to tokens (They are currently in shape of words)

In [24]:
print(len(x))
print(len(y))

2860861
2860861


In [25]:
x_tok = np.array([[None for i in range(len(x[0]))] for ii in range(len(x))])
for li,line in enumerate(x):
  for wi, w in enumerate(line):
    x_tok[li][wi] = word2tok[w]

y_tok = []
for w in y:
  y_tok.append(word2tok[w])
  
y_tok = np.array(y_tok)

print(x_tok[:5])
print(y_tok[:5])

[[51719 50848 61587 16425 4345 38289]
 [50848 61587 54787 4345 38289 59304]
 [61587 54787 16425 38289 59304 13094]
 [54787 16425 4345 59304 13094 2812]
 [16425 4345 38289 13094 2812 50754]]
[54787 16425  4345 38289 59304]


In [26]:
x_tok = x_tok.flatten()
print(x_tok)
print(len(x_tok))

[51719 50848 61587 ... 15941 41142 63565]
17165166


In [27]:
y_tok2 = []
for i in y_tok:
  for count in range(6):
    y_tok2.append(i)

y_tok2 = np.array(y_tok2)

print(y_tok2[:40])
print(len(y_tok2))

[54787 54787 54787 54787 54787 54787 16425 16425 16425 16425 16425 16425
  4345  4345  4345  4345  4345  4345 38289 38289 38289 38289 38289 38289
 59304 59304 59304 59304 59304 59304 13094 13094 13094 13094 13094 13094
  2812  2812  2812  2812]
17165166


In [28]:
# X one-hot encoding
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(np.array(list(tok2word.keys()))[:,np.newaxis])

x_tok_m = np.array(x_tok)[:,np.newaxis]
x_tok_m_onehot = enc.transform(x_tok_m)
x_tok_m_onehot

<17165166x64080 sparse matrix of type '<class 'numpy.float64'>'
	with 17165166 stored elements in Compressed Sparse Row format>

In [29]:
# Y one-hot encoding
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(np.array(list(tok2word.keys()))[:,np.newaxis])

y_tok_m = np.array(y_tok2)[:,np.newaxis]
y_tok_m_onehot = enc.transform(y_tok_m)
y_tok_m_onehot

<17165166x64080 sparse matrix of type '<class 'numpy.float64'>'
	with 17165166 stored elements in Compressed Sparse Row format>

In [30]:
print(x_tok_m_onehot.shape)
print(y_tok_m_onehot.shape)

(17165166, 64080)
(17165166, 64080)


NN Model Training with Tensorflow

In [31]:
import tensorflow as tf

In [72]:
# One to One implementation (Without TF Embedding layer)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, input_shape=(None,64080)),
    # tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64080, activation='softmax',use_bias=False)
    # tf.keras.layers.Softmax()
])

In [73]:
model.compile(tf.keras.optimizers.Adam(learning_rate=0.005)
,loss = tf.keras.losses.CategoricalCrossentropy()
# ,loss='mse'
)

In [74]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, None, 50)          3204050   
                                                                 
 dense_11 (Dense)            (None, None, 64080)       3204000   
                                                                 
Total params: 6,408,050
Trainable params: 6,408,050
Non-trainable params: 0
_________________________________________________________________


In [75]:
print(x_tok_m_onehot.shape)
print(y_tok_m_onehot.shape)

(17165166, 64080)
(17165166, 64080)


In [76]:
x_tf = x_tok_m_onehot[:1000].toarray().astype('float32')
y_tf = y_tok_m_onehot[:1000].toarray().astype('float32')

print(x_tf.shape)
print(y_tf.shape)

(1000, 64080)
(1000, 64080)


In [77]:
x_tf = tf.expand_dims(x_tf, 1)
y_tf = tf.expand_dims(y_tf, 1)

print(x_tf.shape)
print(y_tf.shape)

(1000, 1, 64080)
(1000, 1, 64080)


In [78]:
model.fit(x_tf , y_tf, batch_size=16, epochs = 20)

Epoch 1/20
63/63 [==============================] - 5s 64ms/step - loss: 9.2274
Epoch 2/20
63/63 [==============================] - 5s 73ms/step - loss: 4.8186
Epoch 3/20
63/63 [==============================] - 4s 58ms/step - loss: 4.7476
Epoch 4/20
63/63 [==============================] - 4s 67ms/step - loss: 4.7061
Epoch 5/20
63/63 [==============================] - 4s 64ms/step - loss: 4.6933
Epoch 6/20
63/63 [==============================] - 4s 66ms/step - loss: 4.6329
Epoch 7/20
63/63 [==============================] - 4s 64ms/step - loss: 4.5307
Epoch 8/20
63/63 [==============================] - 4s 63ms/step - loss: 4.3323
Epoch 9/20
63/63 [==============================] - 4s 58ms/step - loss: 4.0487
Epoch 10/20
63/63 [==============================] - 4s 59ms/step - loss: 3.7117
Epoch 11/20
63/63 [==============================] - 4s 58ms/step - loss: 3.4058
Epoch 12/20
63/63 [==============================] - 4s 59ms/step - loss: 3.1752
Epoch 13/20
63/63 [==================

In [85]:
w = model.trainable_variables
print(w[0].shape)
print(w[1].shape)
print(w[2].shape)

emb = w[0]

(64080, 50)
(50,)
(50, 64080)


In [89]:
def get_embedding(embedding_matrice, word, word2tok):
  word_indice = word2tok[word]
  embedding_dim = embedding_matrice.shape[1]
  vocab_size = embedding_matrice.shape[0]
  word_onehot = np.zeros(shape=(vocab_size))
  word_onehot[word_indice] = 1.0
  wordvec = np.matmul(word_onehot, embedding_matrice)

  return wordvec

In [90]:
get_embedding(emb, 'tehran', word2tok)

array([-0.00038042,  0.00095071,  0.00209366,  0.00553201, -0.00820794,
       -0.00939974, -0.00188599, -0.00121959, -0.0035228 , -0.00730685,
        0.00782984,  0.00165427,  0.0083894 ,  0.00655011, -0.00035508,
        0.00727489,  0.00802968, -0.00960241, -0.00608108, -0.00197033,
        0.0055131 , -0.0039534 ,  0.00015099,  0.00905157,  0.00703726,
       -0.00438353, -0.00450746,  0.00454774, -0.0077984 ,  0.00223712,
        0.00193642,  0.00404981, -0.0075534 ,  0.00706257, -0.004321  ,
       -0.00735936,  0.00493398, -0.00220352, -0.00249753,  0.00700572,
       -0.00828908,  0.00071427,  0.00637341,  0.00670215,  0.00058311,
       -0.0094409 , -0.00423089, -0.00237358, -0.00178957, -0.00737061])

In [132]:
def closest_words(word, embedding_matrice, word2tok, n=10):
  emb_target_word = get_embedding(embedding_matrice, word, word2tok)
  closest = []
  
  for counter, i in enumerate(word2tok.keys()):
    emb_word = get_embedding(embedding_matrice, i, word2tok)
    dist = np.linalg.norm(emb_target_word - emb_word)
    if len(closest) < 10:
      closest.append((i,float(f'{dist:.5f}')))
    else:
      if dist < max([i[1] for i in closest]):
        closest.append((i,float(f'{dist:.5f}')))
      closest = sorted(closest, key= lambda x: x[1])
      closest = closest[:10]
    if counter % 200 == 0:
      print(f'{counter}/{len(word2tok)}', closest, sep=' => ')

  return closest

In [140]:
diiis = closest_words('tehran', emb, word2tok)

0
500
1000
1500
2000
2500
3000
3500
4000
4500


KeyboardInterrupt: ignored